#!/bin/bash
echo "==================================="
echo "ПУШИ КОД НА GITHUB"
echo "==================================="
echo ""
echo "Выполни эти команды:"
echo ""
echo "cd /Users/abramous/Desktop/chatbot-ui-custom"
echo "git remote add origin https://github.com/abramflow/chatbot-ui-simple.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Когда GitHub попросит:"
echo "- Username: твой GitHub username (например: abramflow)"
echo "- Password: НЕ ПАРОЛЬ, а Personal Access Token (создай на https://github.com/settings/tokens)"
echo ""
echo "==================================="
